language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install requests
# command to run tests
script:
  - python setup.py test # or py.test for Python versions 3.5 and below
